### ISSUE TITLE
Hi !

### ISSUE THREAD

**Issue by Raf-sns** [kravets-levko/php-shoutcast#1]
Hi !
I am looking for an application capable of creating a stream for a "Radio-Cisba" web-radio, we are an association and we broadcast a local web-radio.

We are looking for a solution that could be self-hosted, we are on a shared server, your script seems to be the solution.

Is it functional? How can I set it up? I went through the code, I can see roughly what it does but I can't see how to set the entry and exit points of the stream.

Cordially,
Raf

**Comment by kravets-levko** [comment]
Hi @Raf-sns!

First of all, thank you for the interest to this project 😅 Unfortunately, it's rather not functional at all. At some point, I created it just to play with Shoutcast protocol, but later lost an interest to it. At this moment, I'm not even conding in PHP anymore. I'm sorry that I didn't help you, hopefully you'll find other tool that fits you needs
